name = "control-de-citas"
main = "src/index.js"
compatibility_date = "2025-09-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "control-de-citas-db"
database_id = "2b827e45-bfef-4646-bbc3-23ffe75c9534"
